// app.js – Simple client‑side router & UI logic for MyGallery
// ---------------------------------------------------------------
// This script is loaded on every page (index.html, category.html, album.html, photo.html)
// It fetches the generated data.json, parses URL parameters and renders the appropriate view.
// It also handles navigation, zoom, and metadata toggles.

// Global data holder
let galleryData = null;

// Utility: get query parameters as an object
function getQueryParams() {
    const params = {};
    const search = window.location.search.substring(1);
    if (!search) return params;
    search.split('&').forEach(pair => {
        const [key, value] = pair.split('=');
        if (key) params[decodeURIComponent(key)] = decodeURIComponent(value || '');
    });
    return params;
}

// Fetch the manifest (public/data.json). All pages are served from the same root, so we can use a relative path.
async function loadData() {
    try {
        const resp = await fetch('data.json');
        if (!resp.ok) throw new Error('Failed to load data.json');
        galleryData = await resp.json();
        applyBranding(); // Apply globally
        route();
    } catch (e) {
        console.error(e);
        document.getElementById('main-content').innerHTML = `<div class="alert alert-danger">Unable to load gallery data.</div>`;
    }
}

// Router – decide which view to render based on query params
// Router – decide which view to render based on query params or page context
function route() {
    const params = getQueryParams();

    // Check specific pages based on unique DOM elements
    const isCategoryPage = !!document.getElementById('category-title');
    const isAlbumPage = !!document.getElementById('album-title');
    const isPhotoPage = !!document.getElementById('photo-title');
    const isHomePage = !!document.getElementById('categories');

    if (isPhotoPage) {
        if (params.album && params.photo) {
            renderPhoto(params.album, params.photo);
        } else {
            showError('Missing album or photo parameter.');
        }
    } else if (isAlbumPage) {
        if (params.album) {
            renderAlbum(params.album);
        } else {
            showError('Missing album parameter.');
        }
    } else if (isCategoryPage) {
        if (params.category) {
            renderCategory(params.category);
        } else {
            showError('Missing category parameter.');
        }
    } else if (isHomePage) {
        renderHome();
    }
}

function showError(msg) {
    const main = document.getElementById('main-content');
    if (main) main.innerHTML = `<div class="alert alert-danger">${msg}</div>`;
}

// ---------- Rendering functions ----------
// ---------- Rendering functions ----------
function applyBranding() {
    const cfg = galleryData.config || {};
    if (cfg.projectName) {
        document.title = cfg.projectName;
        const brand = document.querySelector('.navbar-brand');
        if (brand) {
            // Logo + Text
            brand.innerHTML = `
                ${cfg.projectLogo ? `<img src="${cfg.projectLogo}" alt="Logo" width="30" height="30" class="d-inline-block align-text-top me-2">` : ''}
                ${cfg.projectName}
            `;
        }
    }
    if (cfg.browserIcon) {
        let link = document.querySelector("link[rel~='icon']");
        if (!link) {
            link = document.createElement('link');
            link.rel = 'icon';
            document.head.appendChild(link);
        }
        link.href = cfg.browserIcon;
    }
}

function renderHome() {
    applyBranding();
    const container = document.getElementById('categories');
    if (!container) return;
    container.innerHTML = '';

    // Use the categories map generated by build.js
    const catMap = galleryData.categories || {};
    const catList = Object.keys(catMap);

    // Layout
    const layout = (galleryData.config && galleryData.config.layout) || 'grid';
    container.className = 'layout-' + layout;

    // Switch to container-fluid for modern layouts to use full width
    const parentContainer = container.parentElement;
    if (parentContainer && (parentContainer.classList.contains('container') || parentContainer.classList.contains('container-fluid'))) {
        if (layout === 'grid') {
            parentContainer.classList.add('container');
            parentContainer.classList.remove('container-fluid', 'px-4');
        } else {
            parentContainer.classList.remove('container');
            parentContainer.classList.add('container-fluid', 'px-4');
        }
    }

    catList.forEach(cat => {
        const cover = catMap[cat]; // Resolved path from build.js
        const col = document.createElement('div');
        col.className = 'gallery-item'; // Generic item wrapper
        col.innerHTML = `
      <a href="category.html?category=${encodeURIComponent(cat)}" class="text-decoration-none">
        <div class="category-card">
            ${cover ? `<img src="${cover}" alt="${cat}">` : '<div class="w-100 h-100 bg-secondary"></div>'}
            <div class="category-overlay">
                <h5 class="category-title-overlay">${cat}</h5>
            </div>
        </div>
      </a>`;
        container.appendChild(col);
    });
}

function renderCategory(category) {
    const title = document.getElementById('category-title');
    if (title) {
        // Add back button to title area if not already there (though easier to do in HTML)
        title.textContent = `Category: ${category}`;
    }
    const container = document.getElementById('albums');
    if (!container) return;
    container.innerHTML = '';
    const albums = galleryData.albums.filter(a => (a.categories || []).includes(category));

    const layout = (galleryData.config && galleryData.config.layout) || 'grid';
    container.className = 'layout-' + layout;

    // Switch to container-fluid for modern layouts
    const parentContainer = container.parentElement;
    if (parentContainer && (parentContainer.classList.contains('container') || parentContainer.classList.contains('container-fluid'))) {
        if (layout === 'grid') {
            parentContainer.classList.add('container');
            parentContainer.classList.remove('container-fluid', 'px-4');
        } else {
            parentContainer.classList.remove('container');
            parentContainer.classList.add('container-fluid', 'px-4');
        }
    }

    albums.forEach(album => {
        const col = document.createElement('div');
        col.className = 'gallery-item';

        let coverSrc = '';
        if (album.cover) {
            coverSrc = `thumbnails/${album.cover}`;
        } else if (galleryData.config && galleryData.config.defaultAlbumCover) {
            coverSrc = galleryData.config.defaultAlbumCover;
        }

        const count = album.images ? album.images.length : 0;

        col.innerHTML = `
      <a href="album.html?album=${encodeURIComponent(album.id)}&category=${encodeURIComponent(category)}" class="album-item">
        <div class="album-thumb-wrapper">
             ${coverSrc ? `<img src="${coverSrc}" alt="${album.title}" onerror="this.onerror=null; this.src='${galleryData.config.defaultAlbumCover || ''}';">` : '<div class="w-100 h-100 bg-secondary"></div>'}
        </div>
        <div class="album-title">${album.title}</div>
        <div class="album-count">${count} items</div>
      </a>`;
        container.appendChild(col);
    });
}

// Security Helpers
async function sha256(message) {
    const msgBuffer = new TextEncoder().encode(message);
    const hashBuffer = await crypto.subtle.digest('SHA-256', msgBuffer);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

function checkLock(album) {
    if (!album.locked) return true;
    if (localStorage.getItem('unlocked_' + album.id) === 'true') return true;
    return false;
}

function showUnlockPrompt(album) {
    const main = document.getElementById('main-content');
    if (!main) return;

    const dict = galleryData.dictionary || {};
    const txtTitle = dict.lockedTitle || 'Locked Album';
    const txtMsg = dict.lockedMsg || 'This album requires a code to access.';
    const txtPlaceholder = dict.enterCodePlaceholder || 'Enter Access Code';
    const txtBtn = dict.unlockBtn || 'Unlock';
    const txtError = dict.incorrectCode || 'Incorrect code';
    const txtBack = dict.backToGallery || 'Back to Gallery';
    const txtWaiting = dict.waitingUnlock || 'Waiting to unlock: ';

    main.innerHTML = `
        <div class="container d-flex justify-content-center align-items-center" style="min-height: 60vh;">
            <div class="card p-4 shadow-lg text-center" style="max-width: 400px; width: 100%;">
                <div class="mb-3">
                    <ion-icon name="lock-closed-outline" size="large"></ion-icon>
                </div>
                <h4 class="mb-3">${txtTitle}</h4>
                <p class="text-muted mb-2">${txtMsg}</p>
                <p class="fw-bold mb-4">${txtWaiting}${album.title}</p>
                <div class="mb-3">
                     <input type="password" id="unlock-code" class="form-control text-center" placeholder="${txtPlaceholder}" autofocus>
                </div>
                <button id="unlock-btn" class="btn btn-primary w-100">${txtBtn}</button>
                <div id="unlock-error" class="text-danger mt-2 small" style="display:none;">${txtError}</div>
                <div class="mt-3">
                    <a href="index.html" class="text-decoration-none small text-secondary">${txtBack}</a>
                </div>
            </div>
        </div>
    `;

    const btn = document.getElementById('unlock-btn');
    const input = document.getElementById('unlock-code');
    const err = document.getElementById('unlock-error');

    const handleUnlock = async () => {
        const code = input.value;
        if (!code) return;

        // Clear previous error
        err.style.display = 'none';

        const codeHash = await sha256(code);
        const masterHash = galleryData.config ? galleryData.config.masterHash : null;

        // Check against Album Hash OR Master Hash
        const matchAlbum = album.unlockHash && codeHash === album.unlockHash;
        const matchMaster = masterHash && codeHash === masterHash;

        if (matchAlbum || matchMaster) {
            localStorage.setItem('unlocked_' + album.id, 'true');
            // Reload page to restore full UI structure and re-run checkLock (which will now pass)
            window.location.reload();
        } else {
            err.style.display = 'block';
            input.value = '';
            input.focus();
        }
    };

    btn.onclick = handleUnlock;
    input.onkeyup = (e) => {
        if (e.key === 'Enter') handleUnlock();
    };
}

function renderAlbum(albumId) {
    const params = getQueryParams(); // Need access to 'category' param
    const album = galleryData.albums.find(a => a.id === albumId);
    if (!album) {
        document.getElementById('main-content').innerHTML = `<div class="alert alert-warning">Album not found.</div>`;
        return;
    }

    if (!checkLock(album)) {
        showUnlockPrompt(album);
        return;
    }
    const title = document.getElementById('album-title');
    if (title) title.textContent = album.title;

    // Configure Back Button
    const backLink = document.getElementById('back-link');
    if (backLink) {
        if (params.category) {
            backLink.href = `category.html?category=${encodeURIComponent(params.category)}`;
        } else {
            backLink.href = `index.html`; // Default fallback
        }
    }
    const container = document.getElementById('photos');
    if (!container) return;
    container.innerHTML = '';

    const layout = (galleryData.config && galleryData.config.layout) || 'grid';
    container.className = 'layout-' + layout;

    // Switch to container-fluid for modern layouts
    const parentContainer = container.parentElement;
    if (parentContainer && (parentContainer.classList.contains('container') || parentContainer.classList.contains('container-fluid'))) {
        if (layout === 'grid') {
            parentContainer.classList.add('container');
            parentContainer.classList.remove('container-fluid', 'px-4');
        } else {
            parentContainer.classList.remove('container');
            parentContainer.classList.add('container-fluid', 'px-4');
        }
    }

    album.images.forEach(img => {
        const col = document.createElement('div');
        col.className = 'gallery-item';
        const thumb = img.thumb;
        // Make the whole card clickable
        col.innerHTML = `
      <a href="photo.html?album=${encodeURIComponent(album.id)}&photo=${encodeURIComponent(img.name)}" class="text-decoration-none text-dark">
        <div class="card h-100 album-card-hover">
            <img src="${thumb}" class="card-img-top" alt="${img.name}">
        </div>
      </a>`;
        container.appendChild(col);
    });
}

// Global Panzoom instance
let panzoomInstance = null;

function renderPhoto(albumId, imageName) {
    const album = galleryData.albums.find(a => a.id === albumId);
    if (!album) {
        document.getElementById('main-content').innerHTML = `<div class="alert alert-warning">Album not found.</div>`;
        return;
    }

    if (!checkLock(album)) {
        window.location.href = `album.html?album=${encodeURIComponent(albumId)}`;
        return;
    }
    const title = document.getElementById('photo-title');
    if (title) title.textContent = `${album.title} – ${imageName}`;

    const container = document.getElementById('photo-container');
    if (!container) return;

    // Find image object by name
    const imgObj = album.images.find(img => img.name === imageName);
    if (!imgObj) {
        container.innerHTML = '<div class="text-white">Image not found.</div>';
        return;
    }

    // Render split images without gaps (d-flex is enough, no spacing classes)
    container.innerHTML = `
            <div class="d-flex" style="transform-origin: center;">
      <img src="${imgObj.srcA}" draggable="false" alt="Part A" />
      <img src="${imgObj.srcB}" draggable="false" alt="Part B" />
    </div>`;

    // Initialize Panzoom
    if (panzoomInstance) panzoomInstance.dispose();
    const elem = container.querySelector('.d-flex');
    // Wait for images to load for proper sizing, but init immediately for responsiveness
    panzoomInstance = Panzoom(elem, {
        maxScale: 5,
        minScale: 0.1,
        contain: 'outside',
        startScale: 1
    });
    // Enable mouse wheel
    elem.parentElement.addEventListener('wheel', panzoomInstance.zoomWithWheel);

    // Keyboard shortcuts for Zoom (Moved to global listener to avoid duplication, keeping specific ones here if needed, but better consolidated)
    // Removed local keydown listener to correct logic placement.


    // Navigation logic
    const idx = album.images.findIndex(img => img.name === imageName);
    const prevIdx = (idx - 1 + album.images.length) % album.images.length;
    const nextIdx = (idx + 1) % album.images.length;

    const navPrev = document.getElementById('nav-prev');
    const navNext = document.getElementById('nav-next');
    const backBtn = document.getElementById('back-btn');

    // Back to Album
    backBtn.onclick = () => {
        window.location.href = `album.html?album=${encodeURIComponent(album.id)}`;
    };

    // Unbind old listeners to avoid duplicates (simple assignment overwrites)
    navPrev.onclick = () => {
        window.location.search = `?album=${encodeURIComponent(album.id)}&photo=${encodeURIComponent(album.images[prevIdx].name)}`;
    };
    navNext.onclick = () => {
        window.location.search = `?album=${encodeURIComponent(album.id)}&photo=${encodeURIComponent(album.images[nextIdx].name)}`;
    };

    // Info Logic
    const infoBtn = document.getElementById('info-btn');
    const infoPanel = document.getElementById('info-panel');
    const infoOverlay = document.getElementById('info-overlay');
    const closeInfoBtn = document.getElementById('close-info-btn');
    const wrapper = document.getElementById('photo-wrapper');
    const overlayTitle = document.getElementById('overlay-title');

    // Set default overlay title
    // Logic: Title from MD > Filename without extension
    const metaTitle = imgObj.meta && imgObj.meta.title ? imgObj.meta.title : '';
    const cleanName = imgObj.name.replace(/\.[^/.]+$/, ""); // Remove extension
    overlayTitle.textContent = metaTitle || cleanName;

    const overlayDesc = document.getElementById('overlay-desc');
    if (overlayDesc) {
        overlayDesc.textContent = imgObj.meta && imgObj.meta.description ? imgObj.meta.description : '';
    }

    // Render metadata content
    const meta = imgObj.meta || {};
    const titleHtml = meta.title ? `<div class="fw-bold text-white mb-2" style="font-size: 1.1rem;">${meta.title}</div>` : '';

    // Format tags: "Tag: tag1, tag2"
    let tagsHtml = '';
    if (meta.tags && meta.tags.length > 0) {
        tagsHtml = `<div class="text-white-50 mb-3" style="font-size: 0.9rem;"><span class="text-white fw-bold">Tags:</span> ${meta.tags.join(', ')}</div>`;
    }

    // Description + Content
    // Description + Content
    const descHtml = meta.description ? `<p class="mb-2">${meta.description}</p>` : '';
    const contentHtml = meta.content || '';

    const finalHtml = `
        ${titleHtml}
        ${tagsHtml}
        <div id="metadata-text" class="text-white-50" style="font-size: 0.95rem;">
            ${descHtml}
            ${contentHtml}
        </div>
        `;

    document.getElementById('metadata-content').innerHTML = finalHtml || '<p class="text-white-50">No metadata found.</p>';

    function toggleInfo(show) {
        if (show) {
            infoPanel.style.transform = 'translateX(0)';
            infoOverlay.style.opacity = '0'; // Hide bottom overlay
            // Shrink photo wrapper
            wrapper.style.width = 'calc(100% - 320px)';
            wrapper.style.marginRight = '320px';
            // Shift Next button
            navNext.classList.add('shifted');
            localStorage.setItem('infoOpen', 'true');
        } else {
            infoPanel.style.transform = 'translateX(100%)';
            infoOverlay.style.opacity = '1'; // Show bottom overlay
            wrapper.style.width = '100%';
            wrapper.style.marginRight = '0';
            navNext.classList.remove('shifted');
            localStorage.setItem('infoOpen', 'false');
        }
        // Resize panzoom after layout change
        setTimeout(() => panzoomInstance.resize(), 300);
    }

    infoBtn.onclick = () => {
        const isHidden = infoPanel.style.transform === 'translateX(100%)';
        toggleInfo(isHidden);
    };

    // Restore state from localStorage
    if (localStorage.getItem('infoOpen') === 'true') {
        toggleInfo(true);
    }

    // Copy Button Logic
    const copyBtn = document.getElementById('copy-btn');
    if (copyBtn) {
        copyBtn.onclick = async () => {
            const textElem = document.getElementById('metadata-text');
            const textToCopy = textElem ? textElem.innerText : '';
            if (textToCopy) {
                try {
                    await navigator.clipboard.writeText(textToCopy);
                    // Visual feedback
                    const originalIcon = copyBtn.innerHTML;
                    copyBtn.innerHTML = '<ion-icon name="checkmark-outline" style="font-size: 16px;"></ion-icon>';
                    setTimeout(() => {
                        copyBtn.innerHTML = originalIcon;
                    }, 2000);
                } catch (err) {
                    console.error('Failed to copy text: ', err);
                }
            }
        };
    }
}

// Initialise when DOM is ready
// Initialise when DOM is ready
document.addEventListener('DOMContentLoaded', () => {
    loadData();
    setupGlobalInteractions();
});

function setupGlobalInteractions() {
    // Only active on Photo Page
    if (!document.getElementById('photo-title')) return;

    document.addEventListener('keydown', (e) => {
        // Ignore if user is typing in an input (unlikely here but good practice)
        if (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA') return;

        // Navigation
        if (e.key === 'ArrowLeft') {
            document.getElementById('nav-prev')?.click();
        } else if (e.key === 'ArrowRight') {
            document.getElementById('nav-next')?.click();
        }
        // Info Toggle
        else if (e.key === 'i' || e.key === 'I') {
            document.getElementById('info-btn')?.click();
        }
        // Zoom Controls (Global shortcuts)
        else if (panzoomInstance) {
            if (e.key === 'Escape') panzoomInstance.reset();
            if (e.key === '+' || e.key === '=') panzoomInstance.zoomIn();
            if (e.key === '-') panzoomInstance.zoomOut();
            if (e.key === '0') panzoomInstance.reset();
        }
    });

    document.addEventListener('wheel', (e) => {
        // check if hovering over the zoomable image container
        // If inside photo-container, let Panzoom or default scroll happen (Panzoom handles wheel usually)
        if (e.target.closest('#photo-container')) return;

        // Otherwise (black background), use wheel for navigation
        if (e.deltaY < 0) {
            // Scroll Up -> Previous
            document.getElementById('nav-prev')?.click();
        } else if (e.deltaY > 0) {
            // Scroll Down -> Next
            document.getElementById('nav-next')?.click();
        }
    });
}
